### PR TITLE
Update ignored json keys to prevent crash

### PR DESCRIPTION
**Pull request by Evesy**
## Pull Request Checklist

RE https://github.com/sensu-plugins/sensu-plugins-twemproxy/issues/2

Tested using Sensu 0.29 & Twemproxy 0.41.

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose

Ignore additional keys in twemproxy's metrics output so that this Sensu check does not attempt to loop through something that is not a hash.

https://github.com/sensu-plugins/sensu-plugins-twemproxy/issues/2 for more info

#### Known Compatablity Issues

None

### CODE REVIEW

**Comment by Evesy** [comment]
Build is failing on 1.9.3, however I have also raised https://github.com/sensu-plugins/sensu-plugins-twemproxy/pull/4 which should resolve this.

**Comment by majormoses** [comment]
@Evesy thanks for this. I have merged your other and released. Please rebase, I will review in a minute.

**Comment by majormoses** [comment]
while this does work I think there is a better approach here, I think we should expose this skip_keys option so that in the future any new keys could be ignored by user while waiting for a code change.

**Comment by majormoses** [comment]
I did something very similar to this for redis plugin you can use as a good starting point: https://github.com/sensu-plugins/sensu-plugins-redis/pull/31

**Review by majormoses — CHANGES_REQUESTED** [review]
Lets expose it as an option to allow future remediation without a plugin fix.

**Comment by Evesy** [comment]
@majormoses Got there eventually (I think!)

**Comment by majormoses** [comment]
@Evesy yup it looks like what I was looking for.

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-twemproxy/versions/1.0.1

**Pull request merged**
